/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package mazesolver;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Graphics;

/**
 *
 * @author pawel
 */
public class MazePanel extends javax.swing.JPanel {

    /**
     * Creates new form MazePanel
     */
    public MazePanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    private final int[][] mazeMatrix = {
        {1, 1, 1, 1, 1, 1},
        {1, 0, 0, 0, 0, 1},   
        {1, 1, 1, 0, 1, 1},
        {1, 0, 0, 0, 0, 1},
        {1, 1, 0, 1, 0, 1},
        {1, 1, 1, 1, 1, 1},
        
    };
    
    private final int cellSize = 600/mazeMatrix.length;
    
    @Override
    protected void paintComponent(Graphics cell) {
        Color col=new Color(234,112,44);
        for (int i = 0; i < mazeMatrix.length; i++) {
            for (int j = 0; j < mazeMatrix[i].length; j++) {
                if (mazeMatrix[i][j] == 1) {
                    cell.setColor(col);
                    cell.fillRect(j * cellSize, i * cellSize, cellSize, cellSize);
                }
            }
        }
    }
    
    @Override
    public Dimension getPreferredSize() {
        return new Dimension(mazeMatrix[0].length * cellSize, mazeMatrix[0].length * cellSize);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
